package prj.view.dialog;

import prj.view.panel.PanelCustomer;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import prj.controller.CustomerController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prj.model.Customer;

/**
 *
 * @author anhha
 */
public class AddCustomerFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddGuestFrm
     */
    private boolean isEditing = false;
    private int index;

    private void addPlaceHolder(JTextField txt, String placeHolder) {
        if (!txt.getText().equals(placeHolder)) {
            txt.setForeground(Color.BLACK);
        } else {
            txt.setForeground(Color.GRAY);
        }

        txt.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt.getText().equals(placeHolder)) {
                    txt.setText("");
                    txt.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt.getText().isEmpty()) {
                    txt.setText(placeHolder);
                    txt.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void setPlaceHolder() {
        addPlaceHolder(txtCustomerName, "Nguyễn Văn A");
        addPlaceHolder(txtCustomerDOB, "yyyy");
        addPlaceHolder(txtCustomerPhone, "0123456789");
    }

    private void setTxtCustomerID(String id) {
        txtCustomerID.setText(id);
    }

    private void generateId() {
        txtCustomerID.setEditable(false);
        ArrayList<Customer> list = CustomerController.getInstance().getList();
        int rowCount = list.size();
        if (rowCount == 0) {
            txtCustomerID.setText("KH0" + (rowCount + 1));
            return;
        } else {
            String lastId =list.get(list.size() - 1).getsMaKH().trim();
            int numberId = Integer.parseInt(lastId.replace("KH", ""));
            txtCustomerID.setText("KH0" + (numberId + 1));
        }
//        int row = CustomerController.getInstance().CountingRow();
//        this.setTxtCustomerID("KH0" + (row + 1) + "");
    }

    public AddCustomerFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = false;
        this.setPlaceHolder();
        this.generateId();
    }

    public AddCustomerFrm(int index) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = true;
        this.index = index;
        this.addEditInfo(CustomerController.getInstance().getList().get(index));
    }

    public void addEditInfo(Customer c) {
        // set tung text field tuong ung voi tung getter

        txtCustomerID.setText(c.getsMaKH());
        txtCustomerName.setText(c.getsHoten());
        cmbCustomerSex.setSelectedItem(c.getsGioiTinh());
        txtCustomerDOB.setText(Integer.toString(c.getsNamSinh()));
        txtCustomerPhone.setText(c.getsSdtKH());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_goestid = new javax.swing.JLabel();
        jLabel_guestname = new javax.swing.JLabel();
        jLabel_guestsex = new javax.swing.JLabel();
        jLabel_guestaddress = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnClearCustomer = new javax.swing.JButton();
        btnCancelCustomer = new javax.swing.JButton();
        cmbCustomerSex = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCustomerDOB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm/Sửa Khách hàng");
        setResizable(false);

        jLabel_title.setBackground(new java.awt.Color(79, 102, 107));
        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Khách Hàng");
        jLabel_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_title.setOpaque(true);

        jLabel_goestid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_goestid.setText("Mã khách hàng:");

        jLabel_guestname.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_guestname.setText("Họ tên:");

        jLabel_guestsex.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_guestsex.setText("Giới tính:");

        jLabel_guestaddress.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_guestaddress.setText("Số điện thoại:");

        txtCustomerID.setEditable(false);
        txtCustomerID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        txtCustomerName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtCustomerName.setText("Nguyễn Văn A");
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        txtCustomerPhone.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtCustomerPhone.setText("0123456789");

        btnAddCustomer.setBackground(new java.awt.Color(49, 72, 77));
        btnAddCustomer.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCustomer.setText("Lưu");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnClearCustomer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnClearCustomer.setText("Làm mới");
        btnClearCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCustomerActionPerformed(evt);
            }
        });

        btnCancelCustomer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCancelCustomer.setText("Huỷ");
        btnCancelCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCustomerActionPerformed(evt);
            }
        });

        cmbCustomerSex.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbCustomerSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Năm sinh:");

        txtCustomerDOB.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtCustomerDOB.setText("yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel_guestaddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClearCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCustomerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbCustomerSex, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_guestsex)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel_goestid)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_guestname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel1)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_goestid)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_guestname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCustomerSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_guestsex))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_guestaddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        try {

            String MaKH = txtCustomerID.getText();
            String Hoten = txtCustomerName.getText();
            String GioiTinh = cmbCustomerSex.getItemAt(cmbCustomerSex.getSelectedIndex());
            int NamSinh = Integer.parseInt(txtCustomerDOB.getText());
            String sSDT = txtCustomerPhone.getText();

            Customer customer = new Customer(MaKH, Hoten, GioiTinh, NamSinh, sSDT);

            if (isEditing) {
                CustomerController.getInstance().getList().set(this.index, customer);
                CustomerController.getInstance().deleteFromDatabase(
                        CustomerController.getInstance().getList().get(index)
                );
                CustomerController.getInstance().insertToDatabase(customer);

                this.setVisible(true);

            } else {
                CustomerController.getInstance().getList().add(customer);
                CustomerController.getInstance().insertToDatabase(customer);
                //CustomerController.getInstance().Insert(MaKH, Hoten, GioiTinh, NamSinh, sSDT);
            }

            // lấy ra table tblListPharmacist từ Panel truyền vào dữ liệu từ Controller
            PanelCustomer.getInstance().getTable().setModel(CustomerController.getInstance().toTable());

            // close editing dialog after clicking btnAdd 
            if (isEditing) {
                this.dispose();
                return;
            }

            // clear info after adding successfully
            this.btnClearCustomerActionPerformed(evt);
            this.setPlaceHolder();
            //generate new ID
            this.generateId();
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nhập sai thông tin", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnCancelCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCustomerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelCustomerActionPerformed

    private void btnClearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustomerActionPerformed
        //txtCustomerID.setText("");
        txtCustomerName.setText("");
        cmbCustomerSex.setSelectedIndex(0);
        txtCustomerPhone.setText("");
        txtCustomerDOB.setText("");
        txtCustomerName.requestFocus();
    }//GEN-LAST:event_btnClearCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnCancelCustomer;
    private javax.swing.JButton btnClearCustomer;
    private javax.swing.JComboBox<String> cmbCustomerSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_goestid;
    private javax.swing.JLabel jLabel_guestaddress;
    private javax.swing.JLabel jLabel_guestname;
    private javax.swing.JLabel jLabel_guestsex;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField txtCustomerDOB;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    // End of variables declaration//GEN-END:variables
}
