package prj.view.dialog;

import prj.view.panel.PanelDrug;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import prj.controller.DrugController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prj.model.Drug;

/**
 *
 * @author THAONGAN
 */
public class AddDrugFrm extends javax.swing.JFrame {

    private boolean isEditing = false;
    private int index;

    private void addPlaceHolder(JTextField txt, String placeHolder) {
        if (!txt.getText().equals(placeHolder)) {
            txt.setForeground(Color.BLACK);
        } else {
            txt.setForeground(Color.GRAY);
        }

        txt.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt.getText().equals(placeHolder)) {
                    txt.setText("");
                    txt.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt.getText().isEmpty()) {
                    txt.setText(placeHolder);
                    txt.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void setPlaceHolder() {
        addPlaceHolder(txtDrugName, "Motilium-M");
        addPlaceHolder(txtDrugGroup, "Đường tiêu hoá");
        addPlaceHolder(txtDrugIngr, "Domperidone maleate");
        addPlaceHolder(txtUnit, "Vỉ");
        // addPlaceHolder(txtSupplierID, "NCC001");
    }

    private void setTxtDrugId(String drugid) {
        txtDrugId.setText(drugid);
    }

    private void generateId() {
        txtDrugId.setEditable(false);
        ArrayList<Drug> list = DrugController.getInstance().getList();
        int rowCount = list.size();
        if (rowCount == 0) {
            txtDrugId.setText("THUOC0" + (rowCount + 1) + "");
            return;
        } else {
            String lastId = list.get(list.size() - 1).getsMathuoc().trim();
            int numberId = Integer.parseInt(lastId.replace("THUOC", ""));
            txtDrugId.setText("THUOC0" + (numberId + 1) + "");
        }

//        int row = DrugController.getInstance().CountingRow();
//        this.setTxtDrugId("THUOC0" + (row + 1) + "");
    }

    public AddDrugFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = false;
        this.setPlaceHolder();
        this.generateId();
    }

    public AddDrugFrm(int index) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = true;
        this.index = index;
        this.addEditInfo(DrugController.getInstance().getList().get(index));
    }

    public void addEditInfo(Drug d) {
        // set tung text field tuong ung voi tung getter

        txtDrugId.setText(d.getsMathuoc());
        txtDrugName.setText(d.getsTenthuoc());
        txtDrugGroup.setText(d.getsPhannhom());
        cbbDrugType.setSelectedItem(d.getsPhanloai());
        txtDrugIngr.setText(d.getsThanhphan());
        LocalDate dHanSuDung = LocalDate.parse(d.getdHansudung().toString(),
                DateTimeFormatter.ofPattern("yyyy'-'MM'-'dd"));
        txtExpiredDate.setDate(java.sql.Date.valueOf(dHanSuDung));
        txtUnit.setText(d.getsDVT());
        txtSupplierID.setText(d.getsMancc());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDrug = new javax.swing.JLabel();
        jLabel_drugsid = new javax.swing.JLabel();
        jLabel_drugsname = new javax.swing.JLabel();
        jLabel_group = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jLabel_ingredient = new javax.swing.JLabel();
        jLabel_expirydate = new javax.swing.JLabel();
        jLabel_amount = new javax.swing.JLabel();
        jLabel_supplierid = new javax.swing.JLabel();
        txtDrugId = new javax.swing.JTextField();
        txtDrugName = new javax.swing.JTextField();
        txtDrugGroup = new javax.swing.JTextField();
        txtDrugIngr = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        cbbDrugType = new javax.swing.JComboBox<>();
        btnAddDrug = new javax.swing.JButton();
        btnClearDrug = new javax.swing.JButton();
        btnCancelDrug = new javax.swing.JButton();
        txtExpiredDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm Thuốc");
        setResizable(false);

        lbDrug.setBackground(new java.awt.Color(79, 102, 107));
        lbDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDrug.setForeground(new java.awt.Color(255, 255, 255));
        lbDrug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDrug.setText("Thông tin thuốc");
        lbDrug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDrug.setOpaque(true);

        jLabel_drugsid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_drugsid.setText("Mã thuốc");

        jLabel_drugsname.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_drugsname.setText("Tên thuốc");

        jLabel_group.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_group.setText("Nhóm");

        jLabel_type.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_type.setText("Loại");

        jLabel_ingredient.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_ingredient.setText("Thành phần");

        jLabel_expirydate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_expirydate.setText("Hạn sử dụng");

        jLabel_amount.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_amount.setText("Đơn vị tính");

        jLabel_supplierid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_supplierid.setText("Mã nhà cung cấp");

        txtDrugId.setEditable(false);
        txtDrugId.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDrugId.setText("sinh mã tự động");

        txtDrugName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDrugName.setText("Motilium-M");

        txtDrugGroup.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDrugGroup.setText("Đường tiêu hoá");

        txtDrugIngr.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDrugIngr.setText("Domperidone maleate");

        txtUnit.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtUnit.setText("Vỉ");

        txtSupplierID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        cbbDrugType.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cbbDrugType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuốc kê đơn", "Thuốc không kê đơn", "Thực phẩm chức năng" }));

        btnAddDrug.setBackground(new java.awt.Color(49, 72, 77));
        btnAddDrug.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddDrug.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDrug.setText("Lưu");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });

        btnClearDrug.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnClearDrug.setText("Làm mới");
        btnClearDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDrugActionPerformed(evt);
            }
        });

        btnCancelDrug.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCancelDrug.setText("Huỷ");
        btnCancelDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDrugActionPerformed(evt);
            }
        });

        txtExpiredDate.setDate(new Date());
        txtExpiredDate.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_drugsid)
                            .addComponent(jLabel_drugsname)
                            .addComponent(jLabel_group)
                            .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ingredient)
                            .addComponent(jLabel_expirydate)
                            .addComponent(jLabel_amount)
                            .addComponent(jLabel_supplierid))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDrugId)
                            .addComponent(txtDrugName)
                            .addComponent(txtDrugGroup)
                            .addComponent(txtDrugIngr)
                            .addComponent(txtUnit)
                            .addComponent(cbbDrugType, 0, 304, Short.MAX_VALUE)
                            .addComponent(txtExpiredDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drugsid)
                    .addComponent(txtDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drugsname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_group)
                    .addComponent(txtDrugGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_type)
                    .addComponent(cbbDrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ingredient)
                    .addComponent(txtDrugIngr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_expirydate)
                    .addComponent(txtExpiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_amount)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_supplierid)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        try {

            String sMathuoc = txtDrugId.getText();
            String sTenthuoc = txtDrugName.getText();
            String sPhannhom = txtDrugGroup.getText();
            String sPhanloai = cbbDrugType.getItemAt(cbbDrugType.getSelectedIndex());
            String sThanhphan = txtDrugIngr.getText();
            LocalDate dHanSuDung = txtExpiredDate.getDate().toInstant()
                    .atZone(ZoneId.systemDefault()).toLocalDate();
            String sDVT = txtUnit.getText();

            String sMancc = "hello";
            try {
                sMancc = txtSupplierID.getText();
                if (sMancc.isEmpty()) {
                    sMancc = null;
                }
            } catch (Exception e) {

            }
            System.err.println("Mancc la:" + sMancc);

            Drug drug = new Drug(sMathuoc, sTenthuoc, sPhannhom, sPhanloai, sThanhphan,
                    dHanSuDung, sDVT, sMancc);

            if (isEditing) {
                DrugController.getInstance().getList().set(this.index, drug);
                this.setVisible(true);
                DrugController.getInstance().deleteFromDatabase(
                        DrugController.getInstance().getList().get(this.index)
                );
                DrugController.getInstance().insertToDatable(drug);

                //DrugController.getInstance().Delete(DrugController.getInstance().getList().get(this.index).getsMathuoc());
            } else {
                DrugController.getInstance().getList().add(drug);

                dHanSuDung = LocalDate.parse(dHanSuDung.toString(),
                        DateTimeFormatter.ofPattern("yyyy'-'MM'-'dd"));

                DrugController.getInstance().insertToDatable(drug);
//                DrugController.getInstance().Insert(sMathuoc, sTenthuoc, sPhannhom, sPhanloai, sThanhphan,
//                        dHanSuDung.toString(),
//                        sDVT, sMancc);
            }

            PanelDrug.getInstance().getTable().setModel(
                    DrugController.getInstance().toTable()
            );

            // close editing dialog after clicking btnAdd 
            if (isEditing) {
                this.dispose();
                return;
            }

            // clear info after adding successfully
            this.btnClearDrugActionPerformed(evt);
            this.setPlaceHolder();
            //generate new ID
            this.generateId();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nhập sai thông tin", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnCancelDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDrugActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelDrugActionPerformed

    private void btnClearDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDrugActionPerformed
        //txtDrugId.setText("");
        txtDrugName.setText("");
        txtDrugGroup.setText("");
        cbbDrugType.setSelectedIndex(0);
        txtDrugIngr.setText("");
        txtExpiredDate.setDate(new Date());
        txtUnit.setText("");
        txtSupplierID.setText("");
        txtDrugName.requestFocus();
    }//GEN-LAST:event_btnClearDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnCancelDrug;
    private javax.swing.JButton btnClearDrug;
    private javax.swing.JComboBox<String> cbbDrugType;
    private javax.swing.JLabel jLabel_amount;
    private javax.swing.JLabel jLabel_drugsid;
    private javax.swing.JLabel jLabel_drugsname;
    private javax.swing.JLabel jLabel_expirydate;
    private javax.swing.JLabel jLabel_group;
    private javax.swing.JLabel jLabel_ingredient;
    private javax.swing.JLabel jLabel_supplierid;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JLabel lbDrug;
    private javax.swing.JTextField txtDrugGroup;
    private javax.swing.JTextField txtDrugId;
    private javax.swing.JTextField txtDrugIngr;
    private javax.swing.JTextField txtDrugName;
    private com.toedter.calendar.JDateChooser txtExpiredDate;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
