package prj.view.dialog;

import prj.view.panel.PanelPharmacist;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import prj.controller.PharmacistController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prj.model.Pharmacist;

/**
 *
 * @author THAONGAN
 */
public class AddPharmacistFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddPharmacist
     */
    private boolean isEditing = false;
    private int index;

    private void addPlaceHolder(JTextField txt, String placeHolder) {
        if (!txt.getText().equals(placeHolder)) {
            txt.setForeground(Color.BLACK);
        } else {
            txt.setForeground(Color.GRAY);
        }

        txt.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt.getText().equals(placeHolder)) {
                    txt.setText("");
                    txt.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt.getText().isEmpty()) {
                    txt.setText(placeHolder);
                    txt.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void setPlaceHolder() {
        addPlaceHolder(txtPharmacistName, "Nguyễn Văn A");
        addPlaceHolder(txtPharmacistDOB, "yyyy");
        addPlaceHolder(txtPharmacistPhone, "0123456789");
        addPlaceHolder(txtPharmacistAddress, "TP.HCM");
        addPlaceHolder(txtYearWork, "yyyy");
    }

    private void setTxtPharmacisID(String id) {
        this.txtPharmacistID.setText(id);
    }

    private void generateId() {
        txtPharmacistID.setEditable(false);
        ArrayList<Pharmacist> list = PharmacistController.getInstance().getList();
        int rowCount = list.size();
        if (rowCount == 0) {
            txtPharmacistID.setText("NV0" + (rowCount + 1) + "");
            return;
        } else {
            String lastId = list.get(list.size() - 1).getsMaNV().trim();
            int numberId = Integer.parseInt(lastId.replace("NV", ""));
            txtPharmacistID.setText("NV0" + (numberId + 1) + "");
        }

//        int row = PharmacistController.getInstance().CountingRow();
//        this.setTxtPharmacisID("NV0" + (row + 1) + "");
    }

    public AddPharmacistFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = false;
        this.setPlaceHolder();
        this.generateId();

    }

    public AddPharmacistFrm(int index) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = true;
        this.addEditInfo(PharmacistController.getInstance().getList().get(index));
        this.index = index;
    }

    public void addEditInfo(Pharmacist p) {
        // set tung text field tuong ung voi tung getter
        txtPharmacistID.setText(p.getsMaNV());
        txtPharmacistName.setText(p.getsHoTen());
        txtPharmacistDOB.setText(Integer.valueOf(p.getiNamSinh()).toString());
        cmbPharmacistSex.setSelectedIndex(
                (p.getsGioiTinh().equals("Nam")) ? 0
                : (p.getsGioiTinh().equals("Nữ")) ? 1
                : 2
        );
        txtPharmacistPhone.setText(p.getSDT());
        txtPharmacistAddress.setText(p.getsDiaChi());
        txtYearWork.setText(Integer.valueOf(p.getiNamVaoLam()).toString());
        cmbPharmacistShift.setSelectedIndex(p.getiCALV() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPharmacistID = new javax.swing.JTextField();
        txtPharmacistName = new javax.swing.JTextField();
        cmbPharmacistSex = new javax.swing.JComboBox<>();
        txtPharmacistDOB = new javax.swing.JTextField();
        txtPharmacistPhone = new javax.swing.JTextField();
        txtPharmacistAddress = new javax.swing.JTextField();
        txtYearWork = new javax.swing.JTextField();
        cmbPharmacistShift = new javax.swing.JComboBox<>();
        btnAddPharmacist = new javax.swing.JButton();
        btnClearPharmacist = new javax.swing.JButton();
        btnCancelPharmacist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm/Sửa Nhân viên dược sĩ");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(79, 102, 107));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhân viên Dược Sĩ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Giới tính:");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Năm sinh:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("SĐT:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Năm vào làm:");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Ca:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên Nhân viên:");

        txtPharmacistID.setEditable(false);
        txtPharmacistID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPharmacistID.setText("sinh mã tự động");
        txtPharmacistID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPharmacistIDActionPerformed(evt);
            }
        });

        txtPharmacistName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPharmacistName.setText("Nguyễn Văn A");

        cmbPharmacistSex.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbPharmacistSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        txtPharmacistDOB.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPharmacistDOB.setText("yyyy");

        txtPharmacistPhone.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPharmacistPhone.setText("0123456789");

        txtPharmacistAddress.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPharmacistAddress.setText("TP.HCM");

        txtYearWork.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtYearWork.setText("yyyy");

        cmbPharmacistShift.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbPharmacistShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        btnAddPharmacist.setBackground(new java.awt.Color(49, 72, 77));
        btnAddPharmacist.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddPharmacist.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPharmacist.setText("Lưu");
        btnAddPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacistActionPerformed(evt);
            }
        });

        btnClearPharmacist.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnClearPharmacist.setText("Làm mới");
        btnClearPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPharmacistActionPerformed(evt);
            }
        });

        btnCancelPharmacist.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCancelPharmacist.setText("Huỷ");
        btnCancelPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPharmacistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPharmacistShift, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYearWork, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPharmacistAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPharmacistPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPharmacistDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPharmacistSex, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPharmacistID, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPharmacistID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPharmacistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPharmacistSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPharmacistDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPharmacistPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPharmacistAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtYearWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPharmacistShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPharmacistActionPerformed
        //txtPharmacistID.setText("");
        txtPharmacistName.setText("");
        cmbPharmacistSex.setSelectedIndex(0);
        txtPharmacistDOB.setText("");
        txtPharmacistPhone.setText("");
        txtPharmacistAddress.setText("");
        txtYearWork.setText("");
        cmbPharmacistShift.setSelectedIndex(0);
        txtPharmacistName.requestFocus();
    }//GEN-LAST:event_btnClearPharmacistActionPerformed

    private void btnAddPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacistActionPerformed

        try {
            String sMaNV = txtPharmacistID.getText();
            String sHoTen = txtPharmacistName.getText();
            String sGioiTinh = (String) cmbPharmacistSex.getSelectedItem();
            int iNamSinh = Integer.parseInt(txtPharmacistDOB.getText());
            String SDT = txtPharmacistPhone.getText();
            String sDiaChi = txtPharmacistAddress.getText();
            int iNamVaoLam = Integer.parseInt(txtYearWork.getText());
            int iCALV = Integer.valueOf(cmbPharmacistShift.getSelectedItem().toString());

            Pharmacist pharmacist = new Pharmacist(sMaNV, sHoTen, sGioiTinh, iNamSinh,
                    SDT, sDiaChi, iNamVaoLam, iCALV);

            if (isEditing) {
                PharmacistController.getInstance().getList().set(this.index, pharmacist);
                this.setVisible(true);

                PharmacistController.getInstance().deleteFromDatabase(
                        PharmacistController.getInstance().getList().get(this.index)
                );
                PharmacistController.getInstance().insertToDatabase(pharmacist);

                //PharmacistController.getInstance().Delete(PharmacistController.getInstance().getList().get(this.index).getsMaNV());
            } else {
                // thêm vào arraylist trong Controller 1 thằng pharmacist mới
                PharmacistController.getInstance().getList().add(pharmacist);
                PharmacistController.getInstance().insertToDatabase(pharmacist);
                //PharmacistController.getInstance().Insert(sMaNV, sHoTen, sGioiTinh, iNamSinh, SDT, sDiaChi, iNamVaoLam, iCALV);

            }

            // lấy ra table tblListPharmacist từ Panel truyền vào dữ liệu từ Controller
            PanelPharmacist.getInstance().getTable().setModel(
                    PharmacistController.getInstance().toTable()
            );

            if (isEditing) {
                this.dispose();
                return;
            }

            // clear info after adding successfully
            this.btnClearPharmacistActionPerformed(evt);
            this.setPlaceHolder();
            //generate new ID
            this.generateId();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nhập sai thông tin", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAddPharmacistActionPerformed

    private void btnCancelPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPharmacistActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelPharmacistActionPerformed

    private void txtPharmacistIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPharmacistIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPharmacistIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPharmacist;
    private javax.swing.JButton btnCancelPharmacist;
    private javax.swing.JButton btnClearPharmacist;
    private javax.swing.JComboBox<String> cmbPharmacistSex;
    private javax.swing.JComboBox<String> cmbPharmacistShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtPharmacistAddress;
    private javax.swing.JTextField txtPharmacistDOB;
    private javax.swing.JTextField txtPharmacistID;
    private javax.swing.JTextField txtPharmacistName;
    private javax.swing.JTextField txtPharmacistPhone;
    private javax.swing.JTextField txtYearWork;
    // End of variables declaration//GEN-END:variables
}
