package prj.view.dialog;

import prj.view.panel.PanelSupplier;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import prj.controller.SupplierController;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prj.model.Supplier;

/**
 *
 * @author THAONGAN
 */
public class AddSupplierFrm extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplierFrm
     */
    private boolean isEditing = false;
    private int index;

    private void addPlaceHolder(JTextField txt, String placeHolder) {
        if (!txt.getText().equals(placeHolder)) {
            txt.setForeground(Color.BLACK);
        } else {
            txt.setForeground(Color.GRAY);
        }

        txt.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt.getText().equals(placeHolder)) {
                    txt.setText("");
                    txt.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt.getText().isEmpty()) {
                    txt.setText(placeHolder);
                    txt.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void setPlaceHolder() {
        addPlaceHolder(txtSupplierName, "Cty TNHH ABC");
        addPlaceHolder(txtSupplierPhone, "0123456789");
        addPlaceHolder(txtSupplierAddress, "TP.HCM");
        addPlaceHolder(txtSupplierEmail, "info@email.com");

    }

    private void setTxtSupplierID(String id) {
        txtSupplierID.setText(id);
    }

    private void generateId() {
        txtSupplierID.setEditable(false);
        ArrayList<Supplier> list = SupplierController.getInstance().getList();
        int rowCount = list.size();
        if (rowCount == 0) {
            txtSupplierID.setText("NCC0" + (rowCount + 1) + "");
            return;
        } else {
            String lastId = list.get(list.size() - 1).getsMaNCC().trim();
            int numberId = Integer.parseInt(lastId.replace("NCC", ""));
            txtSupplierID.setText("NCC0" + (numberId + 1) + "");
        }

//        int row = SupplierController.getInstance().CountingRow();
//        this.setTxtSupplierID("NCC0" + (row + 1) + "");
    }

    public AddSupplierFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = false;
        this.setPlaceHolder();
        this.generateId();
    }

    public AddSupplierFrm(int index) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isEditing = true;
        this.addEditInfo(SupplierController.getInstance().getList().get(index));
        this.index = index;
    }

    public void addEditInfo(Supplier s) {
        // set tung text field tuong ung voi tung getter
        txtSupplierID.setText(s.getsMaNCC());
        txtSupplierName.setText(s.getsTenNCC());
        txtSupplierPhone.setText(s.getSDT());
        txtSupplierAddress.setText(s.getsDiaChi());
        txtSupplierEmail.setText(s.getsEmail());
        LocalDate dNgayDangKyHD = LocalDate.parse(s.getdNgayDangKyHD().toString(),
                DateTimeFormatter.ofPattern("yyyy'-'MM'-'dd"));
        txtContractSignDate.setDate(java.sql.Date.valueOf(dNgayDangKyHD));
        //txtContractSignDate.setText(dNgayDangKyHD.format(DateTimeFormatter.ofPattern("dd'/'MM'/'yyyy")));
        txtContractExpiredDate.setValue(s.gettThoiHanHD());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_supplierid = new javax.swing.JLabel();
        txtSupplierID = new javax.swing.JTextField();
        txtSupplierName = new javax.swing.JTextField();
        jLabel_supplername = new javax.swing.JLabel();
        jLabel_supplierphonenumber = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel_supplieraddress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSupplierEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnClearSupplier = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnCancelSupplier = new javax.swing.JButton();
        txtContractSignDate = new com.toedter.calendar.JDateChooser();
        txtContractExpiredDate = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel_title.setBackground(new java.awt.Color(79, 102, 107));
        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Nhà Cung Cấp");
        jLabel_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_title.setOpaque(true);

        jLabel_supplierid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_supplierid.setText("Mã nhà cung cấp:");

        txtSupplierID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSupplierID.setText("sinh mã tự động");

        txtSupplierName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSupplierName.setText("Cty TNHH ABC");

        jLabel_supplername.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_supplername.setText("Tên nhà cung cấp:");

        jLabel_supplierphonenumber.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_supplierphonenumber.setText("Điện thoại:");

        txtSupplierPhone.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSupplierPhone.setText("0123456789");

        txtSupplierAddress.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSupplierAddress.setText("TP.HCM");

        jLabel_supplieraddress.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel_supplieraddress.setText("Địa chỉ:");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Email:");

        txtSupplierEmail.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtSupplierEmail.setText("info@email.com");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Ngày ký hợp đồng (dd/mm/yyyy)");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Thời hạn hợp đồng (tháng)");

        btnClearSupplier.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnClearSupplier.setText("Làm mới");
        btnClearSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSupplierActionPerformed(evt);
            }
        });

        btnAddSupplier.setBackground(new java.awt.Color(49, 72, 77));
        btnAddSupplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSupplier.setText("Lưu");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnCancelSupplier.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnCancelSupplier.setText("Huỷ");
        btnCancelSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSupplierActionPerformed(evt);
            }
        });

        txtContractSignDate.setDate(new Date());
        txtContractSignDate.setDateFormatString("dd'/'MM'/'yyyy");

        txtContractExpiredDate.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_supplierid)
                                    .addComponent(jLabel_supplername)
                                    .addComponent(jLabel_supplierphonenumber)
                                    .addComponent(jLabel_supplieraddress)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSupplierName)
                            .addComponent(txtSupplierPhone)
                            .addComponent(txtSupplierAddress)
                            .addComponent(txtSupplierEmail)
                            .addComponent(txtContractExpiredDate)
                            .addComponent(txtContractSignDate, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtSupplierID))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_supplierid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_supplername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_supplierphonenumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_supplieraddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContractSignDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtContractExpiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSupplierActionPerformed
        //txtSupplierID.setText("");
        txtSupplierName.setText("");
        txtSupplierEmail.setText("");
        txtSupplierPhone.setText("");
        txtSupplierAddress.setText("");
        txtContractSignDate.setDate(new Date());
        txtContractExpiredDate.setValue(0);
        txtSupplierName.requestFocus();

    }//GEN-LAST:event_btnClearSupplierActionPerformed

    private void btnCancelSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSupplierActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelSupplierActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        try {
            String sMaNCC = txtSupplierID.getText();
            String sTenNCC = txtSupplierName.getText();
            String SDT = txtSupplierPhone.getText();
            String sDiaChi = txtSupplierAddress.getText();
            String sEmail = txtSupplierEmail.getText();
            // Đổi từ java.util.Date (JCalendar xài) -> java.time.LocalDate (model xài) 
            LocalDate dNgayDangKyHD = txtContractSignDate.getDate().toInstant()
                    .atZone(ZoneId.systemDefault()).toLocalDate();
            int tThoiHanHD = Integer.parseInt(txtContractExpiredDate.getValue().toString());

            Supplier supplier = new Supplier(sMaNCC, sTenNCC,
                    SDT, sDiaChi, sEmail, dNgayDangKyHD, tThoiHanHD);

            if (isEditing) {
                SupplierController.getInstance().getList().set(this.index, supplier);
                this.setVisible(true);
                SupplierController.getInstance().deleteFromDatabase(
                        SupplierController.getInstance().getList().get(this.index)
                );
                SupplierController.getInstance().insertToDatabase(supplier);

//                SupplierController.getInstance().Delete(SupplierController.getInstance()
//                        .getList().get(index).getsMaNCC());
            } else {
                SupplierController.getInstance().getList().add(supplier);
                SupplierController.getInstance().insertToDatabase(supplier);
//                SupplierController.getInstance().Insert(sMaNCC, sTenNCC, SDT, sDiaChi,
//                        sEmail, dNgayDangKyHD.toString(), tThoiHanHD);
            }

            PanelSupplier.getInstance().getTable().setModel(
                    SupplierController.getInstance().toTable()
            );

            if (isEditing) {
                this.dispose();
                return;
            }

            // clear info after adding successfully
            this.btnClearSupplierActionPerformed(evt);
            this.setPlaceHolder();
            //generate new ID
            this.generateId();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Nhập sai thông tin", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnCancelSupplier;
    private javax.swing.JButton btnClearSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_supplername;
    private javax.swing.JLabel jLabel_supplieraddress;
    private javax.swing.JLabel jLabel_supplierid;
    private javax.swing.JLabel jLabel_supplierphonenumber;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JSpinner txtContractExpiredDate;
    private com.toedter.calendar.JDateChooser txtContractSignDate;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierPhone;
    // End of variables declaration//GEN-END:variables
}
